-- Create productboard_users table
CREATE TABLE IF NOT EXISTS productboard_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  productboard_id TEXT,
  email TEXT NOT NULL,
  name TEXT,
  role TEXT,
  workspace_id TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(email, workspace_id)
);

-- Create productboard_products table
CREATE TABLE IF NOT EXISTS productboard_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  productboard_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  workspace_id TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(productboard_id, workspace_id)
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_productboard_users_email ON productboard_users(email);
CREATE INDEX IF NOT EXISTS idx_productboard_users_workspace_id ON productboard_users(workspace_id);
CREATE INDEX IF NOT EXISTS idx_productboard_products_productboard_id ON productboard_products(productboard_id);
CREATE INDEX IF NOT EXISTS idx_productboard_products_workspace_id ON productboard_products(workspace_id);
