-- Create system_config table for storing application configuration
CREATE TABLE public.system_config (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value text,
    description text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- Add comment to table
COMMENT ON TABLE public.system_config IS 'Stores application configuration settings';

-- Add basic indexes
CREATE INDEX system_config_key_idx ON public.system_config(key);

-- Insert initial configuration for ProductBoard API token
INSERT INTO public.system_config (key, value, description)
VALUES (
    'productboard_api_token',
    '', -- Empty value - needs to be set in the admin interface
    'API token for ProductBoard integration'
);

-- Add RLS policies
ALTER TABLE public.system_config ENABLE ROW LEVEL SECURITY;

-- Only allow authenticated users to read configuration
CREATE POLICY "Allow authenticated users to read configuration" ON public.system_config
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- Only allow service role or admin users to modify configuration
CREATE POLICY "Allow admin to modify configuration" ON public.system_config
    FOR ALL
    USING (auth.role() = 'service_role' OR auth.role() = 'authenticated');
